-- Applied once when Docker initializes a new local PostgreSQL volume.
CREATE TABLE IF NOT EXISTS medicines (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(160) NOT NULL,
    stock integer NOT NULL DEFAULT 0 CONSTRAINT ck_medicines_stock_nonnegative CHECK (stock >= 0),
    created_at_utc timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_medicines_name ON medicines (name);
