-- Run once after 001_initial.sql. Safe to rerun. Existing inventory is assigned to
-- an unclaimed legacy tenant (id 1); see database/README.md before migrating data.
BEGIN;
CREATE TABLE IF NOT EXISTS tenants (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(160) NOT NULL,
    created_at_utc timestamptz NOT NULL DEFAULT now()
);
INSERT INTO tenants (id, name) VALUES (1, 'Legacy local inventory') ON CONFLICT (id) DO NOTHING;
SELECT setval(pg_get_serial_sequence('tenants', 'id'), GREATEST((SELECT max(id) FROM tenants), 1));
CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL REFERENCES tenants(id),
    email varchar(254) NOT NULL UNIQUE,
    password_hash text NOT NULL,
    created_at_utc timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE medicines ADD COLUMN IF NOT EXISTS tenant_id bigint;
UPDATE medicines SET tenant_id = 1 WHERE tenant_id IS NULL;
ALTER TABLE medicines ALTER COLUMN tenant_id SET NOT NULL;
ALTER TABLE medicines ADD COLUMN IF NOT EXISTS sku varchar(64) NOT NULL DEFAULT '';
ALTER TABLE medicines ADD COLUMN IF NOT EXISTS sale_price numeric(12,2) NOT NULL DEFAULT 0;
ALTER TABLE medicines ADD COLUMN IF NOT EXISTS cost_price numeric(12,2) NOT NULL DEFAULT 0;
ALTER TABLE medicines ADD COLUMN IF NOT EXISTS reorder_level integer NOT NULL DEFAULT 5;
ALTER TABLE medicines ADD COLUMN IF NOT EXISTS active boolean NOT NULL DEFAULT true;
CREATE INDEX IF NOT EXISTS ix_medicines_tenant_id ON medicines(tenant_id);
CREATE UNIQUE INDEX IF NOT EXISTS ix_medicines_tenant_sku ON medicines(tenant_id, sku) WHERE sku <> '';
CREATE TABLE IF NOT EXISTS sales (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL REFERENCES tenants(id),
    customer varchar(160) NOT NULL,
    total numeric(12,2) NOT NULL CHECK (total >= 0),
    cost_total numeric(12,2) NOT NULL CHECK (cost_total >= 0),
    created_at_utc timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS sale_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id bigint NOT NULL REFERENCES sales(id),
    medicine_id bigint NOT NULL REFERENCES medicines(id),
    medicine_name varchar(160) NOT NULL,
    quantity integer NOT NULL CHECK (quantity > 0),
    unit_price numeric(12,2) NOT NULL CHECK (unit_price >= 0),
    unit_cost numeric(12,2) NOT NULL CHECK (unit_cost >= 0)
);
CREATE TABLE IF NOT EXISTS purchases (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id bigint NOT NULL REFERENCES tenants(id),
    supplier varchar(160) NOT NULL,
    total numeric(12,2) NOT NULL CHECK (total >= 0),
    created_at_utc timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS purchase_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_id bigint NOT NULL REFERENCES purchases(id),
    medicine_id bigint NOT NULL REFERENCES medicines(id),
    medicine_name varchar(160) NOT NULL,
    quantity integer NOT NULL CHECK (quantity > 0),
    unit_cost numeric(12,2) NOT NULL CHECK (unit_cost >= 0)
);
CREATE INDEX IF NOT EXISTS ix_sales_tenant_date ON sales(tenant_id, created_at_utc DESC);
CREATE INDEX IF NOT EXISTS ix_purchases_tenant_date ON purchases(tenant_id, created_at_utc DESC);
COMMIT;
